baseURL = ""
languageCode = "en-us"
title = "The Chronicle"
theme = "chronicle"
uglyURLs = true

[params]
  disqusShortName = "aaronbieber"
  author = "abieber"
  subtitle = "of a ColdFusion Expatriate"
  bio = "Hi, I'm Aaron Bieber. Once, long ago, I wrote ColdFusion for a living. Now I lead software engineers in Boston writing a variety of non-ColdFusion languages."
  recentPosts = 5

[permalinks]
  posts = "/:year/:month/:day/:slug"

[markup]
  [markup.highlight]
    style = "friendly"
